### PR TITLE
add release drafter

### PR DESCRIPTION
**Pull request by manorit2001**
This will help in keeping track of version changes

### CODE REVIEW

**Comment by parth-07** [comment]
@manorit2001 Have you added **bugs** and **features** subcategories in the release-draft template ?

**Comment by manorit2001** [comment]
> @manorit2001 Have you added **bugs** and **features** subcategories in the release-draft template ?

Yes, PRs with `fix` label will be categorised to bug-fixes. PRs with `feature` label will be categorised under `Features`

**Comment by manorit2001** [comment]
Though, one fix is still remaining which is related to branch specific tag pushes https://github.com/XploreX/cgpa-book-android/pull/34. That will probably need to be fixed here also

**Comment by parth-07** [comment]
> Though, one fix is still remaining which is related to branch specific tag pushes [XploreX/cgpa-book-android#34](https://github.com/XploreX/cgpa-book-android/pull/34). That will probably need to be fixed here also

Oh okay.

**Review by parth-07 — APPROVED** [review]
Looks good

**Pull request merged**
