### PR TITLE
Add dev deploy workflow

### LINKED ISSUE #12: CI setup
We can add this https://github.com/marketplace/actions/git-deploy-to-heroku for development and master branch. This will help in testing as well as it will allow the master branch to remain in sync with heroku

### PR DESCRIPTION
**Pull request by parth-07**
This PR adds github workflow for automatic deployment to development server on encountering trigger command in the PR comments. 

Trigger command: `@github deploy`

Github action bot will give _rocket_ reaction to the comment on encountering trigger command, and then _if_ the command is given by a valid user, initiates deployment

Closes #12

### CODE REVIEW

**Comment by parth-07** [comment]
@manorit2001 Can you please check why [deploy](https://probot.github.io/apps/deploy/) isn't triggering deployment event.

**Comment by manorit2001** [comment]
> @manorit2001 Can you please check why [deploy](https://probot.github.io/apps/deploy/) isn't triggering deployment event.

Ah, I just checked. It seems that the project is not that maintained anymore 
https://github.com/helaili/deploy

image

Test and staging environment are abandoned as per this which is causing the issues ig. Let's try to find some other similar project then

**Comment by manorit2001** [comment]
and if not found, we can resort to [this](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) ig

**Comment by parth-07** [comment]
This also seems promising, [https://github.com/marketplace/actions/pull-request-comment-trigger](https://github.com/marketplace/actions/pull-request-comment-trigger), we can perhaps trigger deployment using comment triggers with this.

**Comment by manorit2001** [comment]
> This also seems promising, https://github.com/marketplace/actions/pull-request-comment-trigger, we can perhaps trigger deployment using comment triggers with this.

If we can change settings so that only collaborators can trigger it, then it seems good

**Comment by parth-07** [comment]
deploy

**Comment by manorit2001** [comment]
deploy

**Comment by manorit2001** [comment]
@parth-07 it works!

**Comment by parth-07** [comment]
@manorit2001 yayy :)

**Comment by manorit2001** [comment]
things are being deployed even if we comment in issue, prevent that

**Comment by manorit2001** [comment]
it seems like i can't write the work dep-loyed anymore 😂

**Comment by parth-07** [comment]
@github deploy

**Comment by parth-07** [comment]
@manorit2001 Yes, `@github deploy` works, so I guess we will be tagging github everytime while deploying xD

**Comment by manorit2001** [comment]
deployed again 😂

**Comment by manorit2001** [comment]
and try to prevent running of workflow from issues altogether if possible

**Comment by parth-07** [comment]
@manorit2001 Ideally, it should just match if command is present at start of the comment. But alas, it checks the entire comment body.

**Comment by manorit2001** [comment]
> @manorit2001 Ideally, it should just match if command is present at start of the comment. But alas, it checks the entire comment body.

@github don't deploy

just a check xD

EDIT: ah, atleast it doesn't match things like a subsequence, that's a plus

**Comment by parth-07** [comment]
> and try to prevent running of workflow from issues altogether if possible

This seems more difficult, `issues_comment` works for both issues and pull requests, it seems internally github treats pull requests as issues only.

**Comment by parth-07** [comment]
> EDIT: ah, atleast it doesn't match things like a subsequence, that's a plus

Yeah seriously, that would be a nighmare xD

**Comment by manorit2001** [comment]
> This seems more difficult, `issues_comment` works for both issues and pull requests, it seems internally github treats pull requests as issues only.

src: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment
we can add this `if` condition ig
```
on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"
```

**Comment by parth-07** [comment]
> > This seems more difficult, `issues_comment` works for both issues and pull requests, it seems internally github treats pull requests as issues only.
> 
> src: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#issue_comment
> we can add this `if` condition ig
> 
> ```
> on: issue_comment
> 
> jobs:
>   pr_commented:
>     # This job only runs for pull request comments
>     name: PR comment
>     if: ${{ github.event.issue.pull_request }}
>     runs-on: ubuntu-latest
>     steps:
>       - run: |
>           echo "Comment on PR #${{ github.event.issue.number }}"
> 
>   issue_commented:
>     # This job only runs for issue comments
>     name: Issue comment
>     if: ${{ !github.event.issue.pull_request }}
>     runs-on: ubuntu-latest
>     steps:
>       - run: |
>           echo "Comment on issue #${{ github.event.issue.number }}"
> ```

Workflow will still be triggered in these cases, right ? Job will be skipped though.

**Comment by manorit2001** [comment]
> Workflow will still be triggered in these cases, right ? Job will be skipped though.

Ah, makes sense, but the authentication job is still being run, we can skip that also when running things on issue

**Comment by parth-07** [comment]
> > Workflow will still be triggered in these cases, right ? Job will be skipped though.
> 
> Ah, makes sense, but the authentication job is still being run, we can skip that also when running things on issue

Yes agreed, that step should be skipped.

**Comment by parth-07** [comment]
@github deploy

**Comment by parth-07** [comment]
@github deploy

**Comment by manorit2001** [comment]
@github deploy

**Review by manorit2001 — COMMENTED** [review]
Hi, The deployment works fine but I can see some warnings in Github Actions. I know they won't matter much as deployment works fine but I would at least like you to look into it once if you can fix them

**Comment by parth-07** [comment]
> Hi, The deployment works fine but I can see some warnings in Github Actions. I know they won't matter much as deployment works fine but I would at least like you to look into it once if you can fix them

Those warnings cannot be removed, they are due to using `octokit` for making API requests, they are mentioned in the documentation page too [https://github.com/octokit/request-action#warnings](https://github.com/octokit/request-action#warnings)

**Comment by manorit2001** [comment]
> Those warnings cannot be removed, they are due to using `octokit` for making API requests, they are mentioned in the documentation page too https://github.com/octokit/request-action#warnings

Ah, seems right, cool

**Review by manorit2001 — APPROVED** [review]
LGTM

**Pull request merged**
